# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Malaysian Students' Technology Conference - MSTC
description: > # this means to ignore newlines until "baseurl:"
  #MSTC2016 The Malaysian Students’ Technology Conference (MSTC) is the first initiative spearheaded 
  by Malaysian students studying in the UK that serves as a platform for topics that are 
  relevant to STEM (Science, Technology, Engineering and Mathematics).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msiastc.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 1616519665327266

logo: "css/2016_style/img/icon-large.png"

social: 
  name: Malaysian Students' Technology Conference - MSTC
  link: "https://www.facebook.com/malaysianstudentstechnologyconference"

google_site_verification: google3d1dfe2dc5cfa440.html

include: ['_pages', '_speakers-more']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/malaysianstudentstechnologyconference/

# Build settings
markdown: kramdown
permalink: pretty